### PR TITLE
Fixed: Exiting Inklecate with CTRL+C does not return command line text color to normal

### PR DESCRIPTION
**Pull request by bncastle**
Fixed: When using Inklecate -p to play a .ink file:
If the user exits using CTRL+C when a choice is being displayed, the
normal console text foreground color is not restored.

### CODE REVIEW

**Comment by joethephish** [comment]
I think this could be simplified actually. There's no need to cache the normal font colour, since the `Console` API provides `Console.ResetColor ()`. Maybe try that?

**Comment by bncastle** [comment]
I didn't know about `Concole.ResetColor()`. That will indeed simply things.

**Comment by bncastle** [comment]
FYI I've updated this pull request to use Console.ResetColor().

**Comment by joethephish** [comment]
Thanks, merged!

**Pull request merged**
