### PR TITLE
Support for non-ASCII characters for identifier names

### PR DESCRIPTION
**Pull request by ivaylo5ev**
This PR aims to fulfill a request filed as issue #225  that I started working on earlier this year. In general it adds an instruction `ALLOW IDENTIFIER ???` where `???` is a name for a currated non-ASCII character range.

I have added some basic tests to assert the character ranges can be used properly as variable, constant and divert names. In case the feature needs better test handling I can improve the simple ones I've currently written.

### CODE REVIEW

**Comment by joethephish** [comment]
Thanks - this looks cool, and at first glance looks reasonably straightforward and sensible. Unfortunately it won't be a super high priority thing for us to integrate since it's not something that we directly need ourselves, but I would like to accept it at some point when I've had a chance to review properly!

**Comment by ivaylo5ev** [comment]
You're welcome. I'd be happy if this feature one day makes it to ink :)

**Comment by joethephish** [comment]
Oh, one question though: wouldn't it be more straightforward if identifiers could simply include all character ranges from all the sets you specified...? I can't think of any downsides, except perhaps the a bit of slowdown in the compiler when running the identifier rule...

**Comment by fireton** [comment]
That would be a super-cool feature!

**Comment by ivaylo5ev** [comment]
@joethephish it would have been simpler to develop. However, take for example the Cyrillic range. Roughly, it resides within this range: '\u0400' and '\u0489'. Alas, not all of the characters within that range are alpha-numeric symbols that should be included in proper identifier names. Thus, with my approach I alow for precise selection (curration) of the allowed characters. Another benefit is that not the entire range is being stored in memory, just the subset of usable characters.

**Comment by joethephish** [comment]
Okay, yup the exclude functionality so you can properly curate the ranges more precisely is definitely good. But then why not include all of those ranges including all the exclusions in the identifier set? I.e. It's just the "ALLOW" functionality that I'm querying - it could just allow all of them?

**Comment by ivaylo5ev** [comment]
Now I understand what you have in mind -- to enable the ranges by default. I haven't though of that to be honest, I got hooked by the idea of manually enabling them as I think was suggested in the issue. Also, the change seemed less-invasive, as ASCII-only writers would not experience any changes and potential issues would be limited to non-ASCII authors... maybe that was too-defensive thinking. Making them enabled initially will be a no-brainer and I can update the PR.

**Comment by joethephish** [comment]
Great. I definitely would prefer that. In terms of invasiveness i prefer it because it doesn't (really) add any new syntax or complexity to the compiler. It simply broadens the allowable characters that can be used by identifiers. I don't think there will be any impact at all to ascii writers - if they don't use the extra characters, they're doing no harm!

**Comment by ivaylo5ev** [comment]
Allright, here comes an updated version. The character ranges are now automatically available and the `ALLOW IDENTIFIER ????` instruction has been removed.

**Comment by fireton** [comment]
@joethephish, any idea when these changes will be incorporated into a release? 

Perhaps I'm just ignorant and there is the way to build it myself, sorry. I'm just not very familiar with all this. So I simply waiting for the Unity plugin and editor with this feature. :)

**Comment by joethephish** [comment]
Apologies, just been very busy, afraid I don't have an ETA for now. But definitely planning to pull it in!

**Comment by joethephish** [comment]
Okay, merged in, thanks! Will be in next ink release.

**Pull request merged**
