### PR TITLE
Added project to create nuget package, modified tests

### PR DESCRIPTION
**Pull request by ncthbrt**
I added a project to create nuget packages for the Ink engine. It requires that the dotnet cli be installed which is a cross platform build and package manager tool created by Microsoft in its efforts to make .NET  more cross platform. To build the project, either install the visual studio tooling for dotnet core or using the dotnet cli, run `dotnet restore`,  then `dotnet build`  in the directory containing the project.json file. To generate an artifact which you can upload to nuget.org, call `dotnet pack -c Release`

I also modified the tests as they were breaking on my machine due to line ending and relative pathing issues. I apologise in advance if this broke any scripts. Please let me know in the PR, and I'll fix the scripts.

### CODE REVIEW

**Comment by ncthbrt** [comment]
Related: Issue #90

**Comment by ncthbrt** [comment]
Just to keep you updated, I've added the package to nuget: 
https://www.nuget.org/packages/Inkle.Ink.Engine/

If you want upload control I can set you to be the project administrator on nuget.

**Comment by joethephish** [comment]
Thanks!

Can I just check a few things...

* I noticed in `Tests.cs` line 33 there's a path with Windows back slashes rather than forward slashes. Windows/.NET should cope with forward slashes here, right? Do you mind if we change them for consistency in the project?
* On the same line, that path is relative to a folder called "ink". Is that the main repo's directory? If so, I believe it's not necessarily named ink because git doesn't require the outer folder to be named the same as the repo's name (mine isn't for historical project naming reasons!) It's not a problem for me because it's not hitting the code path, but I wanted to check that. Is this line for Travis or for Visual Studio's sake? I'm quite surprised that the working directory starts *outside* the main repo's folder?!
* Just trying to understand exactly how nuget works and your modifications to the project layout (apologies, I'm very much a newbie in this area). Am I right that you've removed Newtonsoft.Json.dll from the project, so that it's downloaded automatically when building? If so, that's issues #1 finally solved :)

From what I can tell your changes all seem to make sense though!

**Comment by ncthbrt** [comment]
For points 1&2 you are absolutely right. I have edited to use a more robust method of setting the working directory. 

So your problems with issue #1 is that shared code doesn't have packages, it is just that a collection of text files. To fix it, Newtonsoft needed to be added to all projects which used the shared code. This way the references aren't required to be absolute.

**Comment by joethephish** [comment]
Great! Including `Newtonsoft.Json.dll` in every project where it's used sounds no problem at all.

One final question: My build script `build_release.command` assumes that `inklecate/bin/Release/Newtonsoft.Json.dll` will exist, after having built the solution, so that it can include it in the final zip. Is that still true?

**Comment by ncthbrt** [comment]
Yes is should. The build process copies all the dependencies into the output folder (in this case Release)

**Comment by joethephish** [comment]
Cool, this all sounds good then - have now merged. Thanks!

**Pull request merged**
