### PR TITLE
Migration to dotnet standard

### PR DESCRIPTION
**Pull request by 13xforever**
This pull request updates the solution and project files and moves everything to the .net core 2.2.
Changes include:
* Everything builds using the new cross-platform .net core toolset, no need for mono, xamarin, and whatnot
* For backwards compatibility some projects use multi-targeting to produce libraries for legacy platforms (I dropped .net framework 3.5 targets, please do tell if they're needed)
  * `ink-engine-runtime` .net standard (legacy nuget target), and .net standard 2.0 (currently recommended lts target)
  * `compiler` targets and .net standard 2.0
  * both `inklecate` and `InkTestBed` target .net core 3.1 (required to produce [self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained))
  * `tests` target .net core 3.1 (running tests from .net standard libraries isn't really supported)
* updated configuration for vs code to create release builds, run tests, etc
* fixed a couple of tests to run in non-unix environment
* significantly improved `.travis` configuration that allows to build and push nuget package for the engine
  (only requires configuring some build parameters in the project settings)

Things I'm not sure about:
* I removed `.shproj` and `.projitems` files, as I'm not sure why, or even if, they're still needed
* on one hand new self-contained executables are giant compared to old mono-generated binaries, but on the other hand it's an officially supported feature and guarantees correct behavior on the target platform, plus .net 5 intends to merge mono and dotnet core projects together, so things might improve in the future

### CODE REVIEW

**Comment by 13xforever** [comment]
ah, oops, this was supposed to be against my own fork for now

**Comment by 13xforever** [comment]
A quick guide how to setup Travis **before** merging this PR:
* Open [project settings in Travis](https://travis-ci.org/inkle/ink/settings)
* Add secure variable `RELEASE_FEED_APIKEY` with your [NuGet API Key](https://www.nuget.org/account/apikeys) (it needs permissions to push new packages and new versions)
* Add regular variable `RELEASE_FEED_SOURCE_URL` with the value `https://www.nuget.org/`
* Variable `RELEASE_BRANCH` is by default set to `master`, it's optional to add

If you want to publish official nightly builds, you will need to do additional setup:
* Add secure variable `NIGHTLY_FEED_APIKEY` and regular variable `NIGHTLY_FEED_SOURCE_URL` (probably the same values as for release, unless you want a separate space like MyGet instead)

This is a recap of the comments from [.travis.yml](./Files#diff-354f30a63fb0907d4ad57269548329e3)

**Comment by joethephish** [comment]
Tentatively, this sounds good! I'm all for moving forward with standards... so long as they don't break anything of course :-)

However, I'm far from an expert on .net versions and compatibility, and based on past experience I've found it easy to get burned by PRs that do an upgrade only to break compatibility with something somewhere, groan.

Hopefully we can make this work though!

Right now when I open up the solution in Visual Studio for Mac and tell it to build, I get this error:

```
/Users/phish/inkle/projects/ink/compiler/CSC: Error CS0006: Metadata file '/Users/phish/inkle/projects/ink/ink-engine-runtime/bin/Debug/netstandard2.0/ink-engine-runtime.dll' could not be found (CS0006) (ink_compiler)
```

[The internet](https://stackoverflow.com/questions/1421862/metadata-file-dll-could-not-be-found) seems to suggest that it's because the projects aren't being referenced correctly, but a quick glance at the dependencies seem to suggest it's all okay...?

In answer to your questions:

`.command` files are convenience build scripts (they're double clickable on macOS):
 * `build_release` should build everything that gets attached to [each release](https://github.com/inkle/ink/releases/latest). Final products are `inklecate_mac.zip` and `inklecate_windows_and_linux.zip` within the ReleaseBinary folder.
* `build_for_inky` builds everything that is needed for [inky](http://www.github.com/inkle/inky) and gets pasted in [here](https://github.com/inkle/inky/tree/master/app/main-process/ink). Currently that's:

        ink-engine-runtime.dll
        ink-engine-runtime.pdb
        ink_compiler.dll
        ink_compiler.pdb
        inklecate.pdb
        inklecate_mac
        inklecate_win.exe

**Comment by 13xforever** [comment]
Do you have [.net core sdk 2.1](https://dotnet.microsoft.com/download) or newer installed? It might give you an error before the first build, but it should build cleanly with vs/vs code/command line.

as for .command files, I'm not familiar with the syntax, and I don't have mac to test, so it would be great if you can run through the usual motions and tell if it works as expected or not.

**Comment by joethephish** [comment]
I had .net core 2.1 initially but it gave me an error so I updated to 2.2, and that’s when I got the error that I pasted above.

Sure, I’ll fix up the .command files then.

**Comment by joethephish** [comment]
Have just been experimenting with this - trying out the workflow in VS Code (which in general I'm happier with as an editor anyway since I use it with Unity).

I've just hit a bit of a bit of a roadblock though. Our existing build workflow for macOS generates a self-contained dependency free executable, with a single executable. Meanwhile, running `dotnet publish -c Release -r osx-x64 --self-contained true inklecate/inklecate.csproj` makes a folder with **186 files** 😬

Apparently [support for single-file distribution is being worked on](https://github.com/dotnet/coreclr/issues/20287) though it sounds like they'll just have a package that gets extracted somehow.

Arguably this shouldn't be a big deal since most of the time this stuff is hidden away - e.g. embedded within Inky, and for people comfortable with command line tools it's okay to simply require them to install dotnet.

For the Unity package we've been calling inklecate via a command line. Probably it should be directly called by Unity via C# script or via DLL. Previously this wasn't possible because of the version of C# that we were using for ink, but we could upgrade this now.

Argh dependencies!

**Comment by joethephish** [comment]
(Oh and Visual Studio for Mac seemed to fix itself, maybe after building via VS Code and/or on command line? Who knows.)

**Comment by 13xforever** [comment]
Yeah, sorry, I'm unable to say anything mac-related unfortunately, but I triple checked on windows and linux, and there doesn't seem to be any problem with project files or anything

**Comment by joethephish** [comment]
I wonder whether it might be possible to simply refine the dependencies? Currently this is what the published file list for inklecate is on Mac. If I remove a clearly non-required file it isn't happy because it looks for everything in its manifest. But clearly the Mac version shouldn't need all sorts of files like `Microsoft.Win32.Registry.dll` and `Microsoft.VisualBasic.dll` etc!

```
Microsoft.CSharp.dll					System.Reflection.DispatchProxy.dll
Microsoft.VisualBasic.dll				System.Reflection.Emit.ILGeneration.dll
Microsoft.Win32.Primitives.dll				System.Reflection.Emit.Lightweight.dll
Microsoft.Win32.Registry.dll				System.Reflection.Emit.dll
SOS.NETCore.dll						System.Reflection.Extensions.dll
System.AppContext.dll					System.Reflection.Metadata.dll
System.Buffers.dll					System.Reflection.Primitives.dll
System.Collections.Concurrent.dll			System.Reflection.TypeExtensions.dll
System.Collections.Immutable.dll			System.Reflection.dll
System.Collections.NonGeneric.dll			System.Resources.Reader.dll
System.Collections.Specialized.dll			System.Resources.ResourceManager.dll
System.Collections.dll					System.Resources.Writer.dll
System.ComponentModel.Annotations.dll			System.Runtime.CompilerServices.VisualC.dll
System.ComponentModel.DataAnnotations.dll		System.Runtime.Extensions.dll
System.ComponentModel.EventBasedAsync.dll		System.Runtime.Handles.dll
System.ComponentModel.Primitives.dll			System.Runtime.InteropServices.RuntimeInformation.dll
System.ComponentModel.TypeConverter.dll			System.Runtime.InteropServices.WindowsRuntime.dll
System.ComponentModel.dll				System.Runtime.InteropServices.dll
System.Configuration.dll				System.Runtime.Loader.dll
System.Console.dll					System.Runtime.Numerics.dll
System.Core.dll						System.Runtime.Serialization.Formatters.dll
System.Data.Common.dll					System.Runtime.Serialization.Json.dll
System.Data.dll						System.Runtime.Serialization.Primitives.dll
System.Diagnostics.Contracts.dll			System.Runtime.Serialization.Xml.dll
System.Diagnostics.Debug.dll				System.Runtime.Serialization.dll
System.Diagnostics.DiagnosticSource.dll			System.Runtime.dll
System.Diagnostics.FileVersionInfo.dll			System.Security.AccessControl.dll
System.Diagnostics.Process.dll				System.Security.Claims.dll
System.Diagnostics.StackTrace.dll			System.Security.Cryptography.Algorithms.dll
System.Diagnostics.TextWriterTraceListener.dll		System.Security.Cryptography.Cng.dll
System.Diagnostics.Tools.dll				System.Security.Cryptography.Csp.dll
System.Diagnostics.TraceSource.dll			System.Security.Cryptography.Encoding.dll
System.Diagnostics.Tracing.dll				System.Security.Cryptography.Native.Apple.a
System.Drawing.Primitives.dll				System.Security.Cryptography.Native.Apple.dylib
System.Drawing.dll					System.Security.Cryptography.Native.OpenSsl.a
System.Dynamic.Runtime.dll				System.Security.Cryptography.Native.OpenSsl.dylib
System.Globalization.Calendars.dll			System.Security.Cryptography.OpenSsl.dll
System.Globalization.Extensions.dll			System.Security.Cryptography.Primitives.dll
System.Globalization.Native.dylib			System.Security.Cryptography.X509Certificates.dll
System.Globalization.dll				System.Security.Principal.Windows.dll
System.IO.Compression.Brotli.dll			System.Security.Principal.dll
System.IO.Compression.FileSystem.dll			System.Security.SecureString.dll
System.IO.Compression.Native.a				System.Security.dll
System.IO.Compression.Native.dylib			System.ServiceModel.Web.dll
System.IO.Compression.ZipFile.dll			System.ServiceProcess.dll
System.IO.Compression.dll				System.Text.Encoding.Extensions.dll
System.IO.FileSystem.AccessControl.dll			System.Text.Encoding.dll
System.IO.FileSystem.DriveInfo.dll			System.Text.RegularExpressions.dll
System.IO.FileSystem.Primitives.dll			System.Threading.Overlapped.dll
System.IO.FileSystem.Watcher.dll			System.Threading.Tasks.Dataflow.dll
System.IO.FileSystem.dll				System.Threading.Tasks.Extensions.dll
System.IO.IsolatedStorage.dll				System.Threading.Tasks.Parallel.dll
System.IO.MemoryMappedFiles.dll				System.Threading.Tasks.dll
System.IO.Pipes.AccessControl.dll			System.Threading.Thread.dll
System.IO.Pipes.dll					System.Threading.ThreadPool.dll
System.IO.UnmanagedMemoryStream.dll			System.Threading.Timer.dll
System.IO.dll						System.Threading.dll
System.Linq.Expressions.dll				System.Transactions.Local.dll
System.Linq.Parallel.dll				System.Transactions.dll
System.Linq.Queryable.dll				System.ValueTuple.dll
System.Linq.dll						System.Web.HttpUtility.dll
System.Memory.dll					System.Web.dll
System.Native.a						System.Windows.dll
System.Native.dylib					System.Xml.Linq.dll
System.Net.Http.Native.a				System.Xml.ReaderWriter.dll
System.Net.Http.Native.dylib				System.Xml.Serialization.dll
System.Net.Http.dll					System.Xml.XDocument.dll
System.Net.HttpListener.dll				System.Xml.XPath.XDocument.dll
System.Net.Mail.dll					System.Xml.XPath.dll
System.Net.NameResolution.dll				System.Xml.XmlDocument.dll
System.Net.NetworkInformation.dll			System.Xml.XmlSerializer.dll
System.Net.Ping.dll					System.Xml.dll
System.Net.Primitives.dll				System.dll
System.Net.Requests.dll					WindowsBase.dll
System.Net.Security.Native.a				ink-engine-runtime.dll
System.Net.Security.Native.dylib			ink-engine-runtime.xml
System.Net.Security.dll					ink_compiler.dll
System.Net.ServicePoint.dll				ink_compiler.pdb
System.Net.Sockets.dll					inklecate
System.Net.WebClient.dll				inklecate.deps.json
System.Net.WebHeaderCollection.dll			inklecate.dll
System.Net.WebProxy.dll					inklecate.runtimeconfig.json
System.Net.WebSockets.Client.dll			libclrjit.dylib
System.Net.WebSockets.dll				libcoreclr.dylib
System.Net.dll						libdbgshim.dylib
System.Numerics.Vectors.dll				libhostfxr.dylib
System.Numerics.dll					libhostpolicy.dylib
System.ObjectModel.dll					libmscordaccore.dylib
System.Private.CoreLib.dll				libmscordbi.dylib
System.Private.DataContractSerialization.dll		libsos.dylib
System.Private.Uri.dll					mscorlib.dll
System.Private.Xml.Linq.dll				netstandard.dll
System.Private.Xml.dll					sosdocsunix.txt
```

**Comment by 13xforever** [comment]
These are transitive dependencies that are loaded automatically by CLR as they're declared in the reference section.

It would be really best just put this off until .net core 3 officially released, then you'll have officially supported publish options to trim unused code _and_ publish as a single executable. Sadly these two options can't work together in current preview 7, but it was planned for preview 8 that should drop soon™.

**Comment by 13xforever** [comment]
I've updated the project to use dotnet core 3.1 sdk, and will look into adding single executable publish tomorrow, but from what I've seen in my other projects, official dependency trimming is ... subpar, and produces giant binaries in the order of 100 MB

**Comment by 13xforever** [comment]
Actually I get anything from ~23 MB for Windows up to ~36 MB for Linux, which is much better than anticipated, although a far cry from the old mono builds.

At least it's an officially supported path, and things might improve in .net 5 when mono will be merged into dotnet core.

**Comment by 13xforever** [comment]
I've updated my first comment to reflect new targeting of dotnet core 3.1

**Comment by joethephish** [comment]
Good work on this!

I just had another try with your latest commits. This might be a known issue, but I just tried your "Create inklecate release" task on macOS and got the following:

```
/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.CrossTargeting.targets(27,5): error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application. [/Users/phish/inkle/projects/ink/ink-engine-runtime/ink-engine-runtime.csproj]
```

**Comment by 13xforever** [comment]
That's interesting, because inklecate project has only one target framework and it builds without any issues on Windows and Linux, so it should only build netcore3.1 target for the ink engine project as a dependency.

I was going to update the .csproj files to remove legacy AssemblyInfo.cs files anyway, so I will look into it.

**Comment by 13xforever** [comment]
I have updated the inklecate project to explicitly target `netstandard2.0` of the engine, so let's hope it will do the trick (never had to do this in any of my projects before though)

**Comment by joethephish** [comment]
And it's in! Thanks so much for your help and patience with this!

**Pull request merged**
