### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by djonsson**
Replaced no-break space with space to fix formatting

### CODE REVIEW

**Comment by joethephish** [comment]
Oh, interesting - where does it break formatting?

**Comment by djonsson** [comment]
I guess the intention is to parse these lines as `H2`. However, due to the no break space these lines are actually showing up in the readme as `## Using inklecate on the command line` and not as a header. See attached screenshot. 

hs-parse

**Comment by joethephish** [comment]
In what viewer? Because on github it's fine:

image

(Not doubting this PR, just interested!)

**Comment by joethephish** [comment]
Ugh, sorry I'm being very stupid - was looking at *your* version rather than the live version!

Thanks for the fix :-)

**Comment by djonsson** [comment]
Hehe, no probs! :)

**Pull request merged**
