### PR TITLE
Add tag support to .tmLanguage file

### PR DESCRIPTION
**Pull request by sequitur**
HIGHLIGHT ALL THE THINGS

Adds support for tags to the .tmLanguage file. Let me know if you find weird edge cases where this would behave badly, but I believe the syntax is straightforward enough that /#.+$/ should adequately match tags?

### CODE REVIEW

**Comment by joethephish** [comment]
While I would've been happy to do a straight merge of this, I'm afraid this is a derived auto-generated file. The file we edit is `ink.YAML-tmLanguage`, and using AAAPackageDev package in Sublime, it can generated the `.tmLanguage`. Sorry!

(But yeah I'd be happy with that regex!)

**Comment by sequitur** [comment]
Ah, I see. I don't have a copy of Sublime to generate a tmLanguage file, would you merge a PR with just a corresponding edit to the Yaml file?

**Comment by sequitur** [comment]
Nevermind, there's a package for VS Code that does what AAAPackageDev does. I checked the generated XML and it works as intended (but feel free to double check before merging).

**Comment by joethephish** [comment]
Great, thanks!

**Comment by sequitur** [comment]
Great - I'll probably have another PR after some time with some more relevant changes, since there's a decent number of things that could be better in the syntax highlighting there.

**Pull request merged**
